import { CITY_GRID, CITY_TOPS_B64 } from '../data/sunspireGrid';
import { SUNSPIRE } from './desertLayout';

// Sunspire's street map (generated by tools/prep-desert.mjs from the city
// model): the highest surface over each 3 m cell, so streets, squares,
// buildings and walls can be told apart without loading the model.

const G = CITY_GRID;
let tops: Uint8Array | null = null;
const data = () => {
  if (!tops) {
    const bin = atob(CITY_TOPS_B64);
    tops = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) tops[i] = bin.charCodeAt(i);
  }
  return tops;
};

export const GRID_NX = G.nx, GRID_NZ = G.nz, GRID_RES = G.res;

/** Height of the highest surface in cell (i, j), metres above the city base; -1 = open sand. */
export function cellTop(i: number, j: number) {
  if (i < 0 || j < 0 || i >= G.nx || j >= G.nz) return -1;
  const v = data()[j * G.nx + i];
  return v === 255 ? -1 : v / 2;
}

/** A street or square: paved, nothing over it higher than a kerb. */
export function isStreet(i: number, j: number) {
  const t = cellTop(i, j);
  return t >= 0 && t <= 1.5;
}

/** World position (x, z) of a cell's centre. */
export function cellWorld(i: number, j: number): [number, number] {
  return [SUNSPIRE.x + G.x0 + (i + 0.5) * G.res, SUNSPIRE.z + G.z0 + (j + 0.5) * G.res];
}

/** Cell under a world position. */
export function worldCell(x: number, z: number): [number, number] {
  return [Math.floor((x - SUNSPIRE.x - G.x0) / G.res), Math.floor((z - SUNSPIRE.z - G.z0) / G.res)];
}

/** Is a world position inside the walled city (a paved cell, a building or a wall)? */
export function inCity(x: number, z: number) {
  const [i, j] = worldCell(x, z);
  return cellTop(i, j) >= 0;
}

/** Street cells, each with how open its surroundings are (squares score high). */
export function streetCells() {
  const out: { i: number; j: number; open: number }[] = [];
  for (let j = 0; j < G.nz; j++) {
    for (let i = 0; i < G.nx; i++) {
      if (!isStreet(i, j)) continue;
      let open = 0;
      for (let b = -3; b <= 3; b++) for (let a = -3; a <= 3; a++) if (isStreet(i + a, j + b)) open++;
      out.push({ i, j, open });
    }
  }
  return out;
}

/** The model's placement: its bounding-box centre sits at Sunspire's centre, base on the pad. */
export const MODEL = { center: G.modelCenter, scale: G.scale };
