import { CITY_GRID, CITY_TOPS_B64 } from '../data/sunspireGrid';
import { SUNSPIRE } from './desertLayout';

// Ghagrabba's street map (generated by tools/prep-desert.mjs from the city
// model): the highest surface over each 3 m cell, so streets, squares,
// buildings and walls can be told apart without loading the model.

const G = CITY_GRID;
let tops: Uint8Array | null = null;
const data = () => {
  if (!tops) {
    const bin = atob(CITY_TOPS_B64);
    tops = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) tops[i] = bin.charCodeAt(i);
  }
  return tops;
};

export const GRID_NX = G.nx, GRID_NZ = G.nz, GRID_RES = G.res;

/** Height of the highest surface in cell (i, j), metres above the city base; -1 = open sand. */
export function cellTop(i: number, j: number) {
  if (i < 0 || j < 0 || i >= G.nx || j >= G.nz) return -1;
  const v = data()[j * G.nx + i];
  return v === 255 ? -1 : v / 2;
}

/** A street or square: paved, nothing over it higher than a kerb. */
export function isStreet(i: number, j: number) {
  const t = cellTop(i, j);
  return t >= 0 && t <= 1.5;
}

/** World position (x, z) of a cell's centre. */
export function cellWorld(i: number, j: number): [number, number] {
  return [SUNSPIRE.x + G.x0 + (i + 0.5) * G.res, SUNSPIRE.z + G.z0 + (j + 0.5) * G.res];
}

/** Cell under a world position. */
export function worldCell(x: number, z: number): [number, number] {
  return [Math.floor((x - SUNSPIRE.x - G.x0) / G.res), Math.floor((z - SUNSPIRE.z - G.z0) / G.res)];
}

/** Is a world position inside the walled city (a paved cell, a building or a wall)? */
export function inCity(x: number, z: number) {
  const [i, j] = worldCell(x, z);
  return cellTop(i, j) >= 0;
}

/** Street cells, each with how open its surroundings are (squares score high). */
export function streetCells() {
  const out: { i: number; j: number; open: number }[] = [];
  for (let j = 0; j < G.nz; j++) {
    for (let i = 0; i < G.nx; i++) {
      if (!isStreet(i, j)) continue;
      let open = 0;
      for (let b = -3; b <= 3; b++) for (let a = -3; a <= 3; a++) if (isStreet(i + a, j + b)) open++;
      out.push({ i, j, open });
    }
  }
  return out;
}

/** The model's placement: its bounding-box centre sits at Ghagrabba's centre, base on the pad. */
export const MODEL = { center: G.modelCenter, scale: G.scale };

// ---- doors ---------------------------------------------------------------------------------------------

export interface CityDoor {
  /** the street cell in front of it */
  i: number;
  j: number;
  /** step from the street into the building */
  di: number;
  dj: number;
  /** world position of the street cell centre, and the yaw facing out of the building */
  x: number;
  z: number;
  yaw: number;
  kind: 'home' | 'shop' | 'tavern' | 'palace';
  name: string;
  keeper?: string;
  seed: number;
}

/** The shops of Ghagrabba: keeper id, keeper name, shop name. They take the doors nearest the bazaar. */
export const CITY_SHOPS: [string, string, string][] = [
  ['gh-smith', 'Sunsmith Hekat', 'The Sunsteel Forge'],
  ['gh-armour', 'Armourer Djau', 'Djau’s Scale & Shield'],
  ['gh-apoth', 'Healer Meritites', 'The House of Balms'],
  ['gh-spice', 'Spicer Nakht', 'Nakht’s Spice House'],
  ['gh-silk', 'Weaver Sitre', 'The Silk Loom'],
  ['gh-jewel', 'Jeweller Paneb', 'Paneb’s Gold'],
  ['gh-scribe', 'Scribe Ipuwer', 'The Scroll House'],
  ['gh-food', 'Cook Baket', 'The Date Palm Kitchen'],
];

let doors: CityDoor[] | null = null;
/** Doors on the city's buildings: a street cell with a house-high block behind it, spaced apart. */
export function cityDoors(): CityDoor[] {
  if (doors) return doors;
  const out: CityDoor[] = [];
  const hash = (i: number, j: number) => ((i * 73856093) ^ (j * 19349663)) >>> 0;
  const cands: { i: number; j: number; di: number; dj: number; h: number }[] = [];
  for (let j = 2; j < G.nz - 2; j++) {
    for (let i = 26; i < G.nx - 30; i++) {
      if (!isStreet(i, j)) continue;
      if (i >= 184 && i <= 249 && j >= 97 && j <= 126) continue; // the court and the east gate
      for (const [di, dj] of [[1, 0], [-1, 0], [0, 1], [0, -1]]) {
        const a = cellTop(i + di, j + dj), b = cellTop(i + 2 * di, j + 2 * dj);
        if (a < 3 || a > 16 || b < 3) continue;
        // Not in a narrow alley: the street continues either side of the door.
        const si = dj, sj = di;
        if (!isStreet(i + si, j + sj) || !isStreet(i - si, j - sj)) continue;
        cands.push({ i, j, di, dj, h: hash(i, j) });
      }
    }
  }
  cands.sort((a, b) => a.h - b.h);
  const taken: [number, number][] = [];
  for (const c of cands) {
    if (taken.some(([ti, tj]) => Math.hypot(ti - c.i, tj - c.j) < 6)) continue;
    taken.push([c.i, c.j]);
    const [x, z] = cellWorld(c.i, c.j);
    out.push({ i: c.i, j: c.j, di: c.di, dj: c.dj, x, z, yaw: Math.atan2(-c.di, -c.dj), kind: 'home', name: 'a house', seed: c.h % 100000 });
    if (out.length >= 120) break;
  }
  // Shops nearest the bazaar square; three taverns spread about.
  const streets = streetCells().filter((c) => c.i < 184 || c.i > 213 || c.j < 97 || c.j > 123);
  const baz = streets.reduce((a, b) => (b.open > a.open ? b : a), streets[0]);
  const byBaz = [...out].sort((a, b) => Math.hypot(a.i - baz.i, a.j - baz.j) - Math.hypot(b.i - baz.i, b.j - baz.j));
  CITY_SHOPS.forEach(([id, , name], k) => {
    const d = byBaz[k];
    d.kind = 'shop';
    d.keeper = id;
    d.name = name;
  });
  const taverns = ['The Thirsty Scarab', 'The Oasis Rest', 'The Last Shade'];
  let t = 0;
  for (const d of out) {
    if (d.kind !== 'home' || t >= taverns.length) continue;
    if (Math.hypot(d.i - baz.i, d.j - baz.j) < 20) continue;
    if (out.some((o) => o.kind === 'tavern' && Math.hypot(o.i - d.i, o.j - d.j) < 60)) continue;
    d.kind = 'tavern';
    d.name = taverns[t++];
  }
  for (const d of out) if (d.kind === 'home') d.name = 'a house of Ghagrabba';
  // The palace: west from the Court of the Sun until the palace front.
  {
    let i = 190;
    const j = 110;
    while (i > 120 && cellTop(i - 1, j) < 3) i--;
    const [x, z] = cellWorld(i, j);
    out.push({ i, j, di: -1, dj: 0, x, z, yaw: Math.atan2(1, 0), kind: 'palace', name: 'the Palace of the Sun', seed: 777 });
  }
  return (doors = out);
}

/** Where a door stands: the street cell, stepped toward the building (refined by a raycast once the city has loaded). */
export function doorFront(d: CityDoor, toWall = 1.3): [number, number] {
  return [d.x + d.di * toWall, d.z + d.dj * toWall];
}
