// The Golden Expanse's assets (desert region, south-west of Elder Glen):
//   node tools/prep-desert.mjs
// - Sunspire, the desert capital: the Egyptian City model with its SketchUp
//   edge lines and preview card removed, simplified, textures recompressed,
//   meshopt geometry -> public/assets/desert/sunspire.glb
// - The sand golem (city guardian) -> public/assets/desert/sandGolem.glb
// - The dune field: the Sand Dunes model rasterised into a 128x128 height
//   tile the terrain repeats across the desert -> src/world/data/duneTile.ts
// Sources: assets-src/incoming/{egyptian_city,sand_golem,sand_dunes}.glb
import fs from 'node:fs';
import path from 'node:path';
import sharp from 'sharp';
import { NodeIO, getBounds } from '@gltf-transform/core';
import { ALL_EXTENSIONS } from '@gltf-transform/extensions';
import { weld, simplify, dedup, prune, flatten, join, textureCompress, meshopt } from '@gltf-transform/functions';
import { MeshoptSimplifier, MeshoptEncoder } from 'meshoptimizer';

const SRC = 'assets-src/incoming';
const OUT = 'public/assets/desert';
await MeshoptSimplifier.ready;
await MeshoptEncoder.ready;
const io = new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({ 'meshopt.encoder': MeshoptEncoder });
fs.mkdirSync(OUT, { recursive: true });

const credit = (doc) => {
  const e = doc.getRoot().getAsset().extras ?? {};
  return `This work is based on "${e.title}" (${e.source ?? ''}) by ${e.author} licensed under ${e.license}\n`;
};
const tris = (doc) => doc.getRoot().listMeshes().reduce((n, m) => n + m.listPrimitives().reduce((k, p) => k + (p.getIndices()?.getCount() ?? p.getAttribute('POSITION').getCount()) / 3, 0), 0);
const licence = [];

// The city's street map: the model rasterised top-down into a 3 m grid of the
// highest surface in each cell (metres above the model's base, after scaling).
// Low cells are streets and squares; tall ones are buildings and walls.
const CITY_SCALE = 0.06, GRID_RES = 3;
function cityGrid(doc) {
  const scene = doc.getRoot().listScenes()[0];
  const b = getBounds(scene);
  const cx = (b.min[0] + b.max[0]) / 2, cz = (b.min[2] + b.max[2]) / 2;
  const NX = Math.ceil(((b.max[0] - b.min[0]) * CITY_SCALE) / GRID_RES) + 1, NZ = Math.ceil(((b.max[2] - b.min[2]) * CITY_SCALE) / GRID_RES) + 1;
  const x0 = (b.min[0] - cx) * CITY_SCALE, z0 = (b.min[2] - cz) * CITY_SCALE;
  const top = new Float32Array(NX * NZ).fill(-1);
  for (const node of doc.getRoot().listNodes()) {
    const mesh = node.getMesh();
    if (!mesh) continue;
    const M = node.getWorldMatrix();
    for (const prim of mesh.listPrimitives()) {
      const pos = prim.getAttribute('POSITION').getArray();
      const idx = prim.getIndices()?.getArray() ?? Uint32Array.from({ length: pos.length / 3 }, (_, i) => i);
      const P = (i) => {
        const x = pos[i * 3], y = pos[i * 3 + 1], z = pos[i * 3 + 2];
        return [(M[0] * x + M[4] * y + M[8] * z + M[12] - cx) * CITY_SCALE, (M[1] * x + M[5] * y + M[9] * z + M[13] - b.min[1]) * CITY_SCALE, (M[2] * x + M[6] * y + M[10] * z + M[14] - cz) * CITY_SCALE];
      };
      for (let t = 0; t < idx.length; t += 3) {
        const A = P(idx[t]), B = P(idx[t + 1]), C = P(idx[t + 2]);
        const hi = Math.max(A[1], B[1], C[1]);
        // Conservative: every cell a triangle's footprint touches takes its highest point.
        const i0 = Math.max(0, Math.floor((Math.min(A[0], B[0], C[0]) - x0) / GRID_RES)), i1 = Math.min(NX - 1, Math.floor((Math.max(A[0], B[0], C[0]) - x0) / GRID_RES));
        const j0 = Math.max(0, Math.floor((Math.min(A[2], B[2], C[2]) - z0) / GRID_RES)), j1 = Math.min(NZ - 1, Math.floor((Math.max(A[2], B[2], C[2]) - z0) / GRID_RES));
        // Big floor slabs span many cells at one height: fine. Tall thin walls: only their own cells.
        for (let j = j0; j <= j1; j++) for (let i = i0; i <= i1; i++) if (hi > top[j * NX + i]) top[j * NX + i] = hi;
      }
    }
  }
  const q = Uint8Array.from(top, (h) => (h < 0 ? 255 : Math.min(254, Math.round(h * 2))));
  fs.writeFileSync('src/world/data/sunspireGrid.ts', `// Generated by tools/prep-desert.mjs: Sunspire's street map. Each ${GRID_RES} m cell holds the highest
// surface over it in half-metres above the city's base (255 = nothing: open sand). x/z run from
// the model's bounding-box centre, scaled by ${CITY_SCALE}.
export const CITY_GRID = { res: ${GRID_RES}, nx: ${NX}, nz: ${NZ}, x0: ${x0.toFixed(2)}, z0: ${z0.toFixed(2)}, modelCenter: [${cx.toFixed(2)}, ${b.min[1].toFixed(2)}, ${cz.toFixed(2)}] as [number, number, number], scale: ${CITY_SCALE} };
export const CITY_TOPS_B64 = '${Buffer.from(q).toString('base64')}';
`);
  console.log('city grid', NX, 'x', NZ);
}

// ---- Sunspire ----------------------------------------------------------------------------------------
{
  const doc = await io.read(path.join(SRC, 'egyptian_city.glb'));
  licence.push(credit(doc));
  // SketchUp exports every edge as a white LINES primitive; the preview card is a 4-triangle quad.
  for (const mesh of doc.getRoot().listMeshes()) {
    for (const prim of mesh.listPrimitives()) {
      const name = prim.getMaterial()?.getName() ?? '';
      const count = (prim.getIndices()?.getCount() ?? prim.getAttribute('POSITION').getCount()) / 3;
      if (prim.getMode() !== 4 || /edge_color/.test(name) || (name === 'material' && count < 10)) {
        mesh.removePrimitive(prim);
        prim.dispose();
      }
    }
    if (!mesh.listPrimitives().length) mesh.dispose();
  }
  // Sandstone, not grey photo stone: warm the base colour a little.
  for (const m of doc.getRoot().listMaterials()) {
    if (/Marble|Brick/.test(m.getName())) m.setBaseColorFactor([1.08, 0.98, 0.84, 1]);
    m.setMetallicFactor(0).setRoughnessFactor(0.95);
  }
  console.log('sunspire: triangles before', Math.round(tris(doc)));
  await doc.transform(
    flatten(),
    join({ keepNamed: false }),
    weld({ tolerance: 0.0005 }),
    simplify({ simplifier: MeshoptSimplifier, ratio: 0.5, error: 0.0006 }),
    dedup(),
    prune(),
    textureCompress({ encoder: sharp, targetFormat: 'webp', resize: [512, 512], quality: 82 }),
  );
  cityGrid(doc);
  await doc.transform(meshopt({ encoder: MeshoptEncoder, level: 'medium' }));
  const b = getBounds(doc.getRoot().listScenes()[0]);
  console.log('sunspire: triangles after', Math.round(tris(doc)), 'bounds', b.min.map(Math.round), b.max.map(Math.round));
  await io.write(path.join(OUT, 'sunspire.glb'), doc);
}

// ---- Sand golem --------------------------------------------------------------------------------------
{
  const doc = await io.read(path.join(SRC, 'sand_golem.glb'));
  licence.push(credit(doc));
  await doc.transform(
    flatten(), weld(), dedup(), prune(),
    textureCompress({ encoder: sharp, targetFormat: 'webp', resize: [1024, 1024], quality: 85 }),
    meshopt({ encoder: MeshoptEncoder, level: 'medium' }),
  );
  await io.write(path.join(OUT, 'sandGolem.glb'), doc);
}

// ---- Dune height tile --------------------------------------------------------------------------------
{
  const doc = await io.read(path.join(SRC, 'sand_dunes.glb'));
  licence.push(credit(doc));
  await doc.transform(flatten());
  const N = 128;
  const H = new Float32Array(N * N).fill(-Infinity);
  const b = getBounds(doc.getRoot().listScenes()[0]);
  const x0 = b.min[0], z0 = b.min[2], sx = (b.max[0] - x0) / (N - 1), sz = (b.max[2] - z0) / (N - 1);
  const v = (a, i) => [a[i * 3], a[i * 3 + 1], a[i * 3 + 2]];
  for (const node of doc.getRoot().listNodes()) {
    const mesh = node.getMesh();
    if (!mesh) continue;
    const M = node.getWorldMatrix();
    const tf = (p) => [M[0] * p[0] + M[4] * p[1] + M[8] * p[2] + M[12], M[1] * p[0] + M[5] * p[1] + M[9] * p[2] + M[13], M[2] * p[0] + M[6] * p[1] + M[10] * p[2] + M[14]];
    for (const prim of mesh.listPrimitives()) {
      const pos = prim.getAttribute('POSITION').getArray();
      const idx = prim.getIndices()?.getArray() ?? Uint32Array.from({ length: pos.length / 3 }, (_, i) => i);
      for (let t = 0; t < idx.length; t += 3) {
        const A = tf(v(pos, idx[t])), B = tf(v(pos, idx[t + 1])), C = tf(v(pos, idx[t + 2]));
        const minI = Math.max(0, Math.floor((Math.min(A[0], B[0], C[0]) - x0) / sx)), maxI = Math.min(N - 1, Math.ceil((Math.max(A[0], B[0], C[0]) - x0) / sx));
        const minJ = Math.max(0, Math.floor((Math.min(A[2], B[2], C[2]) - z0) / sz)), maxJ = Math.min(N - 1, Math.ceil((Math.max(A[2], B[2], C[2]) - z0) / sz));
        const d = (B[2] - C[2]) * (A[0] - C[0]) + (C[0] - B[0]) * (A[2] - C[2]);
        if (Math.abs(d) < 1e-9) continue;
        for (let j = minJ; j <= maxJ; j++) for (let i = minI; i <= maxI; i++) {
          const px = x0 + i * sx, pz = z0 + j * sz;
          const w1 = ((B[2] - C[2]) * (px - C[0]) + (C[0] - B[0]) * (pz - C[2])) / d;
          const w2 = ((C[2] - A[2]) * (px - C[0]) + (A[0] - C[0]) * (pz - C[2])) / d;
          const w3 = 1 - w1 - w2;
          if (w1 < -1e-4 || w2 < -1e-4 || w3 < -1e-4) continue;
          const y = w1 * A[1] + w2 * B[1] + w3 * C[1];
          if (y > H[j * N + i]) H[j * N + i] = y;
        }
      }
    }
  }
  // Holes (none expected) take a neighbour; then normalise to 0..1 around the mean.
  for (let k = 0; k < H.length; k++) if (!isFinite(H[k])) H[k] = H[k - 1] ?? 0;
  let lo = Infinity, hi = -Infinity;
  for (const h of H) (lo = Math.min(lo, h)), (hi = Math.max(hi, h));
  const q = Uint8Array.from(H, (h) => Math.round(((h - lo) / (hi - lo)) * 255));
  const b64 = Buffer.from(q).toString('base64');
  fs.writeFileSync('src/world/data/duneTile.ts', `// Generated by tools/prep-desert.mjs from the Sand Dunes model (${licence[2].trim()})\n// A ${N}x${N} height tile, 0..255 = ${lo.toFixed(2)}..${hi.toFixed(2)} m over ${(b.max[0] - b.min[0]).toFixed(1)} m.\nexport const DUNE_N = ${N};\nexport const DUNE_SPAN = ${(b.max[0] - b.min[0]).toFixed(2)};\nexport const DUNE_RANGE = ${(hi - lo).toFixed(3)};\nexport const DUNE_B64 = '${b64}';\n`);
  console.log('dune tile', N, 'range', (hi - lo).toFixed(2));
}

fs.writeFileSync(path.join(OUT, 'license.txt'), 'Golden Expanse assets (CC-BY 4.0):\n' + licence.join(''));
for (const f of fs.readdirSync(OUT)) console.log(f, (fs.statSync(path.join(OUT, f)).size / 1048576).toFixed(2), 'MB');
